### ISSUE TITLE
C++ Header files missing

### ISSUE THREAD

**Issue by gillins** [conda-forge/awkward-cpp-feedstock#13]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Sorry if I've missed something obvious here...

I have an old project that follows the instructions here: https://awkward-array.org/doc/stable/user-guide/how-to-use-header-only-layoutbuilder.html

This used to work fine with older conda builds of `awkward` but I've just recently tried to get it going again and I'm not having any luck. Not only does `python -m awkward.config --cflags` fail (no `awkward.config`) there doesn't seem to be any builder headers installed at all anymore. 

I understand the code has changed quite a lot recently, so maybe building `awkward` objects in C++ no longer supported?

I wasn't sure if this issue belonged in `awkward-feedstock` or `awkward-cpp-feedstock` but since this is a C++ issue I went with this one. 

### Installed packages

```shell
# packages in environment at /home/sam/miniconda3/envs/awktest:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
awkward                   2.0.8              pyhd8ed1ab_0    conda-forge
awkward-cpp               9               py311ha3edf6b_0    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2022.12.7            ha878542_0    conda-forge
importlib_resources       5.12.0             pyhd8ed1ab_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgfortran-ng            12.2.0              h69a702a_19    conda-forge
libgfortran5              12.2.0              h337968e_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
libsqlite                 3.40.0               h753d276_0    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
numpy                     1.24.2          py311h8e6699e_0    conda-forge
openssl                   3.0.8                h0b41bf4_0    conda-forge
packaging                 23.0               pyhd8ed1ab_0    conda-forge
pip                       23.0.1             pyhd8ed1ab_0    conda-forge
python                    3.11.0          he550d4f_1_cpython    conda-forge
python_abi                3.11                    3_cp311    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
setuptools                67.4.0             pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
typing_extensions         4.4.0              pyha770c72_0    conda-forge
tzdata                    2022g                h191b570_0    conda-forge
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zipp                      3.15.0             pyhd8ed1ab_0    conda-forge
```

### Environment info

```shell
active environment : awktest
    active env location : /home/sam/miniconda3/envs/awktest
            shell level : 3
       user config file : /home/sam/.condarc
 populated config files : /home/sam/.condarc
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.9.7.final.0
       virtual packages : __cuda=11.6=0
                          __linux=5.19.0=0
                          __glibc=2.35=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/sam/miniconda3  (writable)
      conda av data dir : /home/sam/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/sam/miniconda3/pkgs
                          /home/sam/.conda/pkgs
       envs directories : /home/sam/miniconda3/envs
                          /home/sam/.conda/envs
               platform : linux-64
             user-agent : conda/4.11.0 requests/2.27.1 CPython/3.9.7 Linux/5.19.0-32-generic ubuntu/22.04.2 glibc/2.35
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by agoose77** [comment]
@gillins thanks for the report! This is a mistake on our part; at one point we were going to bundle these header files with the Awkward package, but we soon decided that they should be taken directly from our repo, as they are version independent of the awkward packages.

The recommended way to get these headers now is to copy them from the repo: https://github.com/scikit-hep/awkward/tree/main/header-only

Let me know how this goes!

**Comment by gillins** [comment]
Thanks @agoose77 ! I'll have a go at updating my code and see if I can get it running.

**Comment by agoose77** [comment]
Thanks @gillins. I discussed this @jpivarski today, and we plan to publish these headers as a zip archive alongside a `CMakeLists.txt` such that the `ExternalProject` or `add_submodule` approaches work out of the box, hopefully making this less painful for CMake users. I do not know whether this applies to you, but in any case, we can better publish these.

**Comment by gillins** [comment]
Yes this applies to me! Sounds very useful. One other thing i've just noticed - the link to more examples is broken here: https://awkward-array.org/doc/main/user-guide/how-to-use-header-only-layoutbuilder.html#more-examples

**Comment by agoose77** [comment]
Excellent, one fewer bugs in the wild! I'll make a PR, thank you! :)

**Comment by gillins** [comment]
One more question @agoose77 - is there some more documentation or an example on returning an awkward array to Python? Previously, I called `builder.snapshot()` to return a `awkward::ContentPtr` and this was all that was required. The documentation mentions something about allocating memory and using `py::buffer_protocol`, but I must admit you lost me here. Surely there is a relatively easy way where I don't have to learn too much about the details? Thanks!

**Comment by agoose77** [comment]
N.b. that we're exploring a rework of how third-party users include our header-only libraries in [this branch](https://github.com/scikit-hep/awkward/pull/2280).

The problem of allocating memory is to ensure that Python owns the buffers. You can return a view over the memory allocated by `to_buffers` using the [buffer protocol](https://pybind11.readthedocs.io/en/stable/advanced/pycpp/numpy.html#buffer-protocol) or a [memory view](https://pybind11.readthedocs.io/en/stable/advanced/pycpp/numpy.html#memory-view). The former is advantageous in that the Python user doesn't need to know details about the array type, etc. 

However, these arrays are still owned by C++, so their lifetimes are tied to the scope of the C++ program. It's perhaps better in this case to move ownership of the C++ buffers to Python, e.g. https://github.com/pybind/pybind11/issues/2271#issuecomment-650569067

This usually involves some kind of capsule object to free the allocated memory when it goes out of Python scope. I'll do some more digging.

**Comment by agoose77** [comment]
Here's a demo using `scikit-build-core`. If you are not familiar with this Python build backend, don't worry; all the important information is in `demo.cpp`.

**Comment by jpivarski** [comment]
> One more question @agoose77 - is there some more documentation or an example on returning an awkward array to Python? Previously, I called `builder.snapshot()` to return a `awkward::ContentPtr` and this was all that was required. The documentation mentions something about allocating memory and using `py::buffer_protocol`, but I must admit you lost me here. Surely there is a relatively easy way where I don't have to learn too much about the details? Thanks!

ArrayBuilder is glued to Python with pybind11, but RDataFrame's use of it goes through ROOT's cppyy, and some of the potential users of LayoutBuilder wanted to use Cython. (And if [fastjet](https://github.com/scikit-hep/fastjet), which preceeded this, is ever updated to take advantage of it, that one is glued to Python with SWIG.) So we wanted LayoutBuilder to be independent of which Python-C++ glue you use.

For now, I have some instructions on how to do it with pybind11 in https://github.com/impy-project/chromo/issues/65#issue-1374710755. It's the 4-step process starting at

> Moreover, we want NumPy to own the array buffers

More complete instructions for at least two backends would be better, I know. I'll put that on my mental to-do list.

**Comment by agoose77** [comment]
@jpivarski how would you feel about creating an examples directory and placing a near-copy of `demo.zip` there? It needs to be modified for `FetchContent`, but that can happen once 2.1.0 is out.

Then we could also add a Cython backend

**Comment by jpivarski** [comment]
Could it be nested under docs? If that means that this 2 kB ZIP file gets pushed to every version on the documentation server, that's fine.

**Comment by agoose77** [comment]
It could be! To be clear, though, I'd unzip it and make it a subdir so people can browse the code. Do you have other reasons to keep it a zipfile, or is it just from my wording?

**Comment by jpivarski** [comment]
By your wording. I thought it was a zipfile for convenience of users downloading it and trying it out.

**Comment by agoose77** [comment]
My thought was that we create a subdir of the Git repo that can be linked to from the documentation. This would not be easily versioned alongside the documentation (unless we use the `{eval}` role from MyST and pass in the headers version to a `define` for a C++ kernel), but it would provide an example file-system layout. A benefit of this would be that we could also run it in the test suite to ensure that it builds.

We could equally just list the files and their contents in-line.

**Comment by gillins** [comment]
Thanks @agoose77 that demo was very useful! Any chance of an example going in the other direction (awkward array created in Python, being passed to C++)?

**Comment by agoose77** [comment]
@gillins could you elaborate on what you'd like to do there? The only C++ interfaces that we provide for manipulating Awkward Arrays are the RDataFrame headers, which are intended to be jitted. I suppose that if you know the form ahead of time, you could pre-generate the C++ interfaces intended for RDataFrame, though that's not how we originally intended them to be used.

I think our policy for manipulating Awkward Arrays from C++ is either
- Use Python from C++
- Operate on the flat buffers according to your needs

Option (2) is the fastest, but most restrictive. You'd most likely define what kind of array your C++ can work with, e.g. a ragged array of integers, and accept that from the user. If you want to make the user-facing API very high level, you could use the Python API to validate the array form, and then convert it to buffers for use in your application (or, instead of `to_buffers`, flatten it and use `ak.num` to compute the sublist lengths).

@jpivarski might have more to add here depending upon your use case.

**Comment by gillins** [comment]
I guess I was after something like Numpy provides where I could reach into the awkward array and get values out. Obviously in C++ I'd have to cope with each data type and/or layout explicitly or bail if not what expected but this is common with Numpy.
Next best would be `to_buffers` - (if you have an example of this that'd be great) but this would involved copying (?) so potentially slow...

**Comment by agoose77** [comment]
We provide an interface to Numba for fast iteration over Awkward Arrays. Unfortunately we do not offer the same for C++. Perhaps @ianna can weigh in with how feasible it would be to use the RDataFrame generator to build a C++ module to compile. It's certainly possible at a technical level, though I don't know how tied to ROOT it is right now. But, as I say, being able to do something is distinct from whether one _should_ do it.
> Next best would be to_buffers - (if you have an example of this that'd be great) but this would involved copying (?) so potentially slow...

`to_buffers` is "fast" - It should never involve a copy (unless you request a different byteorder). This would produce a series of flat arrays, and you'd use the metadata arrays (indices, offsets, etc) to figure-out how to pull out the values of interest.

It might be helpful to explain the use cases that we might better be able to offer you advice, though :)

**Comment by jpivarski** [comment]
Which `to_buffers`? If you mean the Python function,

https://awkward-array.org/doc/main/reference/generated/ak.to_buffers.html

there are no copies. The buffers this function returns are references to the data in the Awkward Array itself. (Modify them and the Awkward Array will be modified...)

If you mean the C++ method of LayoutBuilder,

https://github.com/scikit-hep/awkward/blob/7fc01d81398dd3ba7bef653768fd6d54d42a38a3/header-only/layout-builder/awkward/LayoutBuilder.h#L135-L144

it copies. Several versions ago, the builder → Python method was a "snapshot" that shared buffers, so that "snapshot" would be a lightweight operation and the builder could continue to build (append only) while an array is in use. However, (a) that required the builder to work through `std::shared_ptr`, rather than `std::unique_ptr`, which was a significant slowdown, (b) shareable buffers must be contiguous, so they had to reallocate-and-copy every time they reached an (exponentially larger) limit; replacing the no-copy snapshot with a copy allowed us to build an array non-contiguously and do the concatenation during the copy-to-arrays. So the fact that it does copy was motivated by speed, in two different ways.

The [ak.from_rdataframe](https://awkward-array.org/doc/main/reference/generated/ak.from_rdataframe.html), [ak.to_rdataframe](https://awkward-array.org/doc/main/reference/generated/ak.to_rdataframe.html) functions are complete and ready for users. The latter is strictly zero-copy: you can iterate over an Awkward Array in C++ by creating an RDataFrame out of it. The Awkward data types have unguessable type names, but they appear in places where you can use `auto`.

I didn't see a tutorial on it in our documentation website, but [these tests](https://github.com/scikit-hep/awkward/blob/main/tests/test_1374_to_rdataframe.py) cover every data type and @ianna presented an [interactive tutorial](https://github.com/ianna/PyHep2022) on it at PyHEP ([video](https://youtu.be/KNop_bDevHQ)).

**Comment by gillins** [comment]
Yes, https://awkward-array.org/doc/main/reference/generated/ak.to_buffers.html - I didn't realise that there was no copy involved - that's perfect. I'll have a go at this - thanks.

Use case is [Satellite Image Segmentation](https://github.com/ubarsc/pyshepseg) which results in data being put into a Raster Attribute Table for the segments. We normally access this in a format independent way using [GDAL's functions](https://gdal.org/doxygen/classGDALDefaultRasterAttributeTable.html) which have Python/Numpy wrappers. However, the [KEA](https://github.com/ubarsc/kealib) format has some other functionality that GDAL doesn't support that I'd like to make available to Python users. What I'm using `awkward` for is the "neighbours" functionality - each segment can have a list of neighbours that can vary greatly in length. So I'm creating functions to read and write neighbours from/to a KEA file for Python users. People end up writing code to crawl around a landscape working out how the segments (and their other attributes) relate to one another.

I've been really impressed with how well awkward arrays work for this use case so I'm keen to push through with this - I really appreciate your help and the hard work getting awkward to this point. The Numba support is really important for us so thanks for putting that in there!

**Comment by jpivarski** [comment]
Actually, I'd like to follow your project and explicitly help out. One of our major goals is to expand Awkward Array beyond particle physics, and this looks like a great match. (Most of the non-physics applications so far have been geographical. That's probably a hint we should pay attention to!)

If you want to ping me on Awkward issues in pyshepseg as they come up, I may be able to help. Incidentally, I worked on a terrain-classification project with hyperspectral images and GDAL about 10 years ago, though we were trying to glue GDAL to Java for Hadoop; Python is easier.

**Comment by gillins** [comment]
Thanks @jpivarski will ping you guys when I have something ready for review. Yes Python is easier!
